name: Github Actions Demo
on: 
  push:
    branches: 
      - main
  pull_request:
      branches: 
      - main
  schedule:
        - cron: "15 06 * * 0"
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name:
        run: echo "the job was triggered by ${{github.event_name }}
      
  
    
    
